version: '3'

services:
  rabbitmq:
    image: 'bitnami/rabbitmq:latest'
    labels:
      kompose.service.type: nodeport
    ports:
      - '4369:4369'
      - '5672:5672'
      - '25672:25672'
      - '15672:15672'
    volumes:
      # - 'rabbitmq_data:/bitnami'
      - 'rabbitmq_data:/opt/rabbitmq/volume/initiative'

volumes:
 rabbitmq_data:
   driver: local
